### ISSUE TITLE
Nested routes

### ISSUE THREAD

**Issue by esso23** [hez2010/BlazorRouter#14]
Nested routes fail with NullReferenceException in method
`private Task SwitchContent(bool isNavigationIntercepted)`
on line with `StateHasChanged()` call. Top-level component is rendered correctly and nested component containing the nested `<Switch>` throws an exception.
Component hierarchy example in https://github.com/hez2010/BlazorRouter/issues/13

**Comment by hez2010** [comment]
Sorry for the delay.
This is a known issue, and I'm planning to fix it in the next version.

**Comment by hez2010** [comment]
Fixed in 12d33590a482fc3c92ae8a6581459cb4955e5f64, please refer to the new document.
