### ISSUE TITLE
Nested routing with nested layouts

### ISSUE THREAD

**Issue by artworkad** [hez2010/BlazorRouter#31]
What is your take on nested layouts? I just tinkered with your library, but I could not make nested layouts work. 

MainLayout:

```
<Switch>
    <Route Template="/nested-route/*">
        <MyUI.Features.FeatureA.Index />
    </Route>
    <Route>
        <h1 class="text-red">Error</h1>
        <p>Sorry, there's nothing at this address.</p>
    </Route>
</Switch>
```

`MyUI/Features/FeatureA/Index/Index.razor`:

```
@page "/feature-a"
@inject NavigationManager NavManager

@code {
    protected override void OnInitialized()
    {
        NavManager.NavigateTo("/feature-a/page-a");
    }
}
```

NestedLayout:

```
<Switch>
    <Route Template="/feature-a/page-a">
        <BlazorUI.Features.FeatureA.PageA/>
    </Route>
    <Route>
        <h1 class="text-danger">Error</h1>
        <p>Nested: Sorry, there's nothing at this address.</p>
    </Route>
</Switch>
```

In PageA I have

    @layout Components.NestedLayout

The content of PageA is loaded, but the layout is completely ignored.

**Comment by hez2010** [comment]
Thanks for reporting this issue. It was caused by the route context required by `@layout` is not present while using `BlazorRouter`. 
Basically, the `@layout` and `@page` directives are only applied to the build-in router, so if you want to nest layout, you can nest your content directly without need of `@layout`.

For example, in the top layout:
```
<div>
  <p>hello from top layout</p>
  <Switch>
    <Route Template="nested-route/*">
      <NestedLayout />
    </Route>
    <Route>
      <p>No nested content found</p>
    </Route>
  </Switch>
</div>

```

In the nested layout:
```
<div>
  <p>hello from nested layout</p>
  <Switch>
    <Route Template="nested-route/foo">
      <p>foo</p>
    </Route>
    <Route Template="nested-route/bar">
      <p>bar</p>
    </Route>
    <Route>
      <p>No content found in nested layout</p>
    </Route>
  </Switch>
</div>
```

**Comment by artworkad** [comment]
@hez2010 awesome! Works now as intended! But it feels a bit like cheating on blazor 😄
